name: Release Asterium Pack

on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Create output dir
      run: mkdir output
    - name: Create full zip
      run: zip -r ${{ github.ref_name }}-full ../texture
      working-directory: ./output
    - name: Create lite zip
      run: zip -r ${{ github.ref_name }}-lite ../texture -x ../texture/assets/minecraft/mcpatcher/*
      working-directory: ./output
    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.name }}
        draft: false
        prerelease: false
    - name: Upload full zip
      id: upload-full-zip
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/${{ github.ref_name }}-full.zip
        asset_name: Asterium-Full-${{ github.ref_name }}.zip
        asset_content_type: application/zip
    - name: Upload full zip
      id: upload-lite-zip
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/${{ github.ref_name }}-lite.zip
        asset_name: Asterium-Lite-${{ github.ref_name }}.zip
        asset_content_type: application/zip
    
